all:
	(cd PR; make )
	(cd PR_NVCC; make )
	(cd PR_novfunc; make )
	(cd PR_novfunc_NVCC; make )
	(cd PR_inline; make )

clean:
	(cd PR; make clean)
	(cd PR_NVCC; make clean)
	(cd PR_novfunc; make clean)
	(cd PR_novfunc_NVCC; make clean)
	(cd PR_inline; make clean)
