all:
	(cd BFSV; make )
	(cd BFSV_NVCC; make )
	(cd BFSV_novfunc; make )
	(cd BFSV_novfunc_NVCC; make )
	(cd BFSV_inline; make )

clean:
	(cd BFSV; make clean)
	(cd BFSV_NVCC; make clean)
	(cd BFSV_novfunc; make clean)
	(cd BFSV_novfunc_NVCC; make clean)
	(cd BFSV_inline; make clean)
