all:
	(cd BFS; make )
	(cd BFS_NVCC; make )
	(cd BFS_novfunc; make )
	(cd BFS_novfunc_NVCC; make )
	(cd BFS_inline; make )

clean:
	(cd BFS; make clean)
	(cd BFS_NVCC; make clean)
	(cd BFS_novfunc; make clean)
	(cd BFS_novfunc_NVCC; make clean)
	(cd BFS_inline; make clean)
