all:
	(cd CCV; make )
	(cd CCV_NVCC; make )
	(cd CCV_novfunc; make )
	(cd CCV_novfunc_NVCC; make )
	(cd CCV_inline; make )

clean:
	(cd CCV; make clean)
	(cd CCV_NVCC; make clean)
	(cd CCV_novfunc; make clean)
	(cd CCV_novfunc_NVCC; make clean)
	(cd CCV_inline; make clean)
