all:
	(cd CC; make )
	(cd CC_NVCC; make )
	(cd CC_novfunc; make )
	(cd CC_novfunc_NVCC; make )
	(cd CC_inline; make )

clean:
	(cd CC; make clean)
	(cd CC_NVCC; make clean)
	(cd CC_novfunc; make clean)
	(cd CC_novfunc_NVCC; make clean)
	(cd CC_inline; make clean)
