all:
	(cd game-of-life; make )
	(cd game-of-life_novfunc; make )
	(cd game-of-life_inline; make )

clean:
	(cd game-of-life; make clean)
	(cd game-of-life_novfunc; make clean)
	(cd game-of-life_inline; make clean)
